# Generated by Django 4.1.3 on 2023-11-26 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='locationTagLink',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
