# Generated by Django 4.1.3 on 2023-11-30 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_post_locationtaglink'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='locationName',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='locationTagLink',
            field=models.TextField(blank=True, null=True),
        ),
    ]
